# Generated by Django 5.1.4 on 2024-12-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll', models.PositiveIntegerField()),
                ('add', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
