# Generated by Django 5.1.4 on 2024-12-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std',
            old_name='add',
            new_name='address',
        ),
    ]
